# Generated by Django 3.2.9 on 2021-12-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='langs',
            field=models.CharField(default='RU', max_length=10, verbose_name='язык'),
        ),
    ]
